# Generated by Django 4.1.5 on 2023-01-25 17:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import employee.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('HR', 'Human Resource'), ('administrative', 'Administrative'), ('software development', 'Software Development'), ('QA', 'Quality Assurance'), ('project management', 'Project Management'), ('Product Management', 'Product Management'), ('design', 'Design'), ('devOps', 'DevOps'), ('customer support', 'Customer Support'), ('marketing', 'Marketing'), ('IT', 'Information Technology')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=15)),
                ('national_id', models.CharField(max_length=50)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to=employee.utils.user_directory_path)),
                ('signature', models.ImageField(upload_to=employee.utils.user_directory_path)),
                ('info_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.PositiveIntegerField()),
                ('conveyance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('house_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mobile_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('salary_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_info', to='employee.employeeinfo')),
            ],
        ),
    ]
