# Generated by Django 4.1.5 on 2023-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_designationinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designationinfo',
            name='designation',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
