# Generated by Django 4.1.5 on 2023-01-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_designationinfo_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
