# Generated by Django 4.1.5 on 2023-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_designationinfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
