# Generated by Django 4.1.5 on 2023-02-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employeesalary_salary_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='basic_salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
