# Generated by Django 4.1.5 on 2023-02-24 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0009_monthlysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepared_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='total_bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='total_diduct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='total_salary',
            field=models.FloatField(null=True),
        ),
    ]
