# Generated by Django 4.1.5 on 2023-02-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_monthlysalary_prepared_by_monthlysalary_total_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='salary_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_salary', to='employee.employeesalary'),
        ),
    ]
