# Generated by Django 4.1.5 on 2023-03-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_monthlysalary_salary_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='exatra_sort_leave',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='extra_late_present',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='total_absence',
            field=models.IntegerField(null=True),
        ),
    ]
