# Generated by Django 4.1.5 on 2023-01-20 18:42

import accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='designets wheter the user can loing to this site', verbose_name='staff_status')),
                ('is_active', models.BooleanField(default=True, help_text='designets wheter the user can loin to this site', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=264)),
                ('last_name', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('photo', models.ImageField(default='default/user.jpg', null=True, upload_to=accounts.utils.user_directory_path)),
                ('date_of_join', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PresentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_village', models.CharField(max_length=50)),
                ('present_post', models.CharField(max_length=50)),
                ('present_upzila', models.CharField(max_length=50)),
                ('present_division', models.CharField(max_length=50)),
                ('present_district', models.CharField(max_length=50)),
                ('present_post_code', models.PositiveIntegerField(default=0)),
                ('address_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='present_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_village', models.CharField(max_length=50)),
                ('permanent_post', models.CharField(max_length=50)),
                ('permanent_upzila', models.CharField(max_length=50)),
                ('present_division', models.CharField(max_length=50)),
                ('permanent_district', models.CharField(max_length=50)),
                ('permanent_post_code', models.PositiveIntegerField(default=0)),
                ('address_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
