# Generated by Django 4.1.5 on 2023-02-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_receptonist',
            field=models.BooleanField(default=False),
        ),
    ]
