# Generated by Django 4.1.5 on 2023-02-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0008_alter_employeesalary_basic_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('entering_time', models.TimeField(blank=True)),
                ('exit_time', models.TimeField(blank=True)),
                ('attendance_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='employee.employeeinfo')),
            ],
        ),
    ]
