# Generated by Django 4.1.5 on 2023-02-04 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employeesalary_basic_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reciption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('leave_hour', models.PositiveIntegerField(default=0)),
                ('outing_time', models.TimeField()),
                ('entering_time', models.TimeField(blank=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sort_leave', to='employee.employeeinfo')),
            ],
        ),
    ]
