# Generated by Django 4.1.5 on 2023-02-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciption', '0003_alter_sortleave_entering_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortleave',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
