# Generated by Django 4.1.5 on 2023-02-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciption', '0004_sortleave_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortleave',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
