# Generated by Django 4.1.5 on 2023-02-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciption', '0007_sortleave_active_status_sortleave_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_present',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
