# Generated by Django 4.1.5 on 2023-02-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciption', '0008_attendance_late_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortleave',
            name='leave_hour',
            field=models.DurationField(),
        ),
    ]
