# Generated by Django 4.1.5 on 2023-02-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciption', '0009_alter_sortleave_leave_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortleave',
            name='late_entry',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
