# Generated by Django 4.1.5 on 2023-03-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciption', '0011_remove_sortleave_entering_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='entering_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
