# Generated by Django 4.1.5 on 2023-03-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciption', '0012_alter_attendance_entering_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='entering_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
