# Generated by Django 4.1.5 on 2023-03-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciption', '0014_alter_attendance_entering_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
