# Generated by Django 4.1.5 on 2023-02-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0003_payrollmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmonth',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
