# Generated by Django 4.1.5 on 2023-02-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0004_payrollmonth_active_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollmonth',
            name='active_status',
        ),
    ]
