# Generated by Django 4.1.5 on 2023-02-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0005_remove_payrollmonth_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmonth',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
