# Generated by Django 4.1.5 on 2023-02-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0008_rename_name_festivalbonus_festival_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalbonus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='festivalbonus',
            name='festival_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
