# Generated by Django 4.1.5 on 2023-02-17 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authority', '0009_festivalbonus_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('leave_description', models.TextField()),
                ('approvied_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('application_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_employee', to=settings.AUTH_USER_MODEL)),
                ('approvied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
