# Generated by Django 4.1.5 on 2023-02-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0011_leaveapplication_declined_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='approvied_status',
            new_name='approved_status',
        ),
    ]
