# Generated by Django 4.1.5 on 2023-02-17 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authority', '0013_alter_leaveapplication_approvied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='approvied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
