# Generated by Django 4.1.5 on 2023-02-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0014_alter_leaveapplication_approvied_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='employee_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
