# Generated by Django 4.1.5 on 2023-02-25 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0016_alter_leaveapplication_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_offday', models.PositiveIntegerField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_month', to='authority.payrollmonth')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=100)),
                ('holiday_date', models.DateField()),
                ('holiday_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_month', to='authority.payrollmonth')),
            ],
        ),
    ]
