# Generated by Django 4.1.5 on 2023-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0018_monthlyholiday_is_active_monthlyoffday_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmonth',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
    ]
