# Generated by Django 4.1.5 on 2023-02-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0019_payrollmonth_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MonthlyPermitedLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permited_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('leave_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_month', to='authority.payrollmonth')),
            ],
        ),
    ]
