# Generated by Django 4.1.5 on 2023-02-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0020_leaveapplication_total_days_monthlypermitedleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypermitedleave',
            name='leave_month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=3),
        ),
    ]
