# Generated by Django 4.1.5 on 2023-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0021_alter_monthlypermitedleave_leave_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypermitedleave',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
