# Generated by Django 4.1.5 on 2023-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0022_monthlypermitedleave_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypermitedleave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='monthlypermitedleave',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
