# Generated by Django 4.1.5 on 2023-02-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0023_alter_monthlypermitedleave_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='application_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
