# Generated by Django 4.1.5 on 2023-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0027_alter_monthlypermitedleave_salary_diduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitedlatepresent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
