# Generated by Django 4.1.5 on 2023-03-01 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0028_permitedlatepresent_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitedlatepresent',
            name='salary_diduction',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
