# Generated by Django 4.1.5 on 2023-03-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0032_remove_permitedsortleave_peremited_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitedsortleave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permitedsortleave',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
