# Generated by Django 4.1.5 on 2023-03-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0033_alter_permitedsortleave_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitedlatepresent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permitedlatepresent',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
