# Generated by Django 4.1.5 on 2023-03-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0036_weklyoffday_notice_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeklyOffday',
            new_name='WeeklyOffday',
        ),
    ]
