# Generated by Django 4.1.5 on 2023-03-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0037_rename_weklyoffday_weeklyoffday'),
    ]

    operations = [
        migrations.AddField(
            model_name='officetime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
